// Theme + tokenizer.
// Adding a language = adding its `setMonarchTokensProvider` here and its
// contribution in EditorPane, without touching the component.

let themeDefined = false;

// Java tokenizer extended from Monaco's base Monarch.
export const javaLanguage = {
  defaultToken: "",
  tokenPostfix: ".java",
  keywords: [
    "abstract", "continue", "for", "new", "switch",
    "assert", "default", "goto", "package", "synchronized",
    "boolean", "do", "if", "private", "this",
    "break", "double", "implements", "protected", "throw",
    "byte", "else", "import", "public", "throws",
    "case", "enum", "instanceof", "return", "transient",
    "catch", "extends", "int", "short", "try",
    "char", "final", "interface", "static", "void",
    "class", "finally", "long", "strictfp", "volatile",
    "const", "float", "native", "super", "while",
    "true", "false", "yield", "record", "sealed",
    "non-sealed", "permits",
  ],
  operators: [
    "=", ">", "<", "!", "~", "?", ":", "==", "<=", ">=", "!=",
    "&&", "||", "++", "--", "+", "-", "*", "/", "&", "|", "^", "%",
    "<<", ">>", ">>>", "+=", "-=", "*=", "/=", "&=", "|=", "^=",
    "%=", "<<=", ">>=", ">>>=",
  ],
  symbols: /[=><!~?:&|+\-*\/\^%]+/,
  escapes: /\\(?:[abfnrtv\\"']|x[0-9A-Fa-f]{1,4}|u[0-9A-Fa-f]{4}|U[0-9A-Fa-f]{8})/,
  digits: /\d+(_+\d+)*/,
  octaldigits: /[0-7]+(_+[0-7]+)*/,
  binarydigits: /[0-1]+(_+[0-1]+)*/,
  hexdigits: /[[0-9a-fA-F]+(_+[0-9a-fA-F]+)*/,
  tokenizer: {
    root: [
      ["non-sealed", "keyword.non-sealed"],
      [/\b(import|package)\b/, "keyword", "@importLine"],
      [
        /[a-zA-Z_$][\w$]*(?=\s*\()/,
        { cases: { "@keywords": { token: "keyword.$0" }, "@default": "method" } },
      ],
      [/[A-Z][\w$]*/, "type"],
      [
        /[a-zA-Z_$][\w$]*/,
        { cases: { "@keywords": { token: "keyword.$0" }, "@default": "variable" } },
      ],
      { include: "@whitespace" },
      [/[{}()\[\]]/, "@brackets"],
      [/[<>](?!@symbols)/, "@brackets"],
      [/@symbols/, { cases: { "@operators": "delimiter", "@default": "" } }],
      [/@\s*[a-zA-Z_\$][\w\$]*/, "annotation"],
      [/(@digits)[eE]([\-+]?(@digits))?[fFdD]?/, "number.float"],
      [/(@digits)\.(@digits)([eE][\-+]?(@digits))?[fFdD]?/, "number.float"],
      [/0[xX](@hexdigits)[Ll]?/, "number.hex"],
      [/0(@octaldigits)[Ll]?/, "number.octal"],
      [/0[bB](@binarydigits)[Ll]?/, "number.binary"],
      [/(@digits)[fFdD]/, "number.float"],
      [/(@digits)[lL]?/, "number"],
      [/[;,.]/, "delimiter"],
      [/"([^"\\]|\\.)*$/, "string.invalid"],
      [/"""/, "string", "@multistring"],
      [/"/, "string", "@string"],
      [/'[^\\']'/, "string"],
      [/(')(@escapes)(')/, ["string", "string.escape", "string"]],
      [/'/, "string.invalid"],
    ],
    importLine: [
      [/;/, "delimiter", "@pop"],
      [/[a-zA-Z_$][\w$]*(?:\.[a-zA-Z_$][\w$]*)*/, "namespace"],
      [/\*/, "namespace"],
      { include: "@whitespace" },
      [/\./, "delimiter"],
    ],
    whitespace: [
      [/[ \t\r\n]+/, ""],
      [/\/\*\*(?!\/)/, "comment.doc", "@javadoc"],
      [/\/\*/, "comment", "@comment"],
      [/\/\/.*$/, "comment"],
    ],
    comment: [
      [/[^\/*]+/, "comment"],
      [/\*\//, "comment", "@pop"],
      [/[\/*]/, "comment"],
    ],
    javadoc: [
      [/[^\/*]+/, "comment.doc"],
      [/\/\*/, "comment.doc.invalid"],
      [/\*\//, "comment.doc", "@pop"],
      [/[\/*]/, "comment.doc"],
    ],
    string: [
      [/[^\\"]+/, "string"],
      [/@escapes/, "string.escape"],
      [/\\./, "string.escape.invalid"],
      [/"/, "string", "@pop"],
    ],
    multistring: [
      [/[^\\"]+/, "string"],
      [/@escapes/, "string.escape"],
      [/\\./, "string.escape.invalid"],
      [/"""/, "string", "@pop"],
      [/./, "string"],
    ],
  },
} as unknown as Record<string, unknown>;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function ensureMiniCodeTheme(monaco: any): void {
  if (themeDefined) return;
  monaco.languages.setMonarchTokensProvider("java", javaLanguage);
  monaco.editor.defineTheme("mini-code-dark", {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "6a7075", fontStyle: "italic" },
      { token: "comment.java", foreground: "6a7075", fontStyle: "italic" },
      { token: "keyword", foreground: "eda05a", fontStyle: "bold" },
      { token: "keyword.flow", foreground: "eda05a", fontStyle: "bold" },
      { token: "type", foreground: "f4bc86" },
      { token: "type.identifier", foreground: "f4bc86" },
      { token: "type.java", foreground: "f4bc86" },
      { token: "method", foreground: "e5c07b" },
      { token: "method.java", foreground: "e5c07b" },
      { token: "variable", foreground: "9cdcfe" },
      { token: "variable.java", foreground: "9cdcfe" },
      { token: "namespace", foreground: "bb9af7" },
      { token: "namespace.java", foreground: "bb9af7" },
      { token: "identifier", foreground: "d4d4d4" },
      { token: "annotation", foreground: "7dcfff" },
      { token: "delimiter", foreground: "a7acaf" },
      { token: "delimiter.java", foreground: "a7acaf" },
      { token: "number", foreground: "e08a3c" },
      { token: "number.float", foreground: "e08a3c" },
      { token: "number.hex", foreground: "e08a3c" },
      { token: "number.octal", foreground: "e08a3c" },
      { token: "number.binary", foreground: "e08a3c" },
      { token: "number.infinity", foreground: "e08a3c" },
      { token: "number.nan", foreground: "e08a3c" },
      { token: "number.date", foreground: "e08a3c" },
      { token: "string", foreground: "c9d97a" },
      { token: "string.escape", foreground: "e08a3c" },
      { token: "string.invalid", foreground: "ff5370", fontStyle: "underline" },
      { token: "string.java", foreground: "c9d97a" },
      { token: "type.yaml", foreground: "f4bc86" },
      { token: "operators", foreground: "eda05a" },
      { token: "tag", foreground: "7dcfff" },
      { token: "namespace.yaml", foreground: "bb9af7" },
      { token: "meta.directive", foreground: "6a7075", fontStyle: "italic" },
      { token: "metatag", foreground: "eda05a" },
      { token: "attribute.name", foreground: "9cdcfe" },
      { token: "attribute.value", foreground: "c9d97a" },
      { token: "strong", fontStyle: "bold" },
      { token: "emphasis", fontStyle: "italic" },
      { token: "string.link", foreground: "7dcfff", fontStyle: "underline" },
      { token: "string.target", foreground: "a7acaf" },
      { token: "meta.separator", foreground: "6a7075" },
    ],
    colors: {
      "editor.background": "#1a1b1c",
      "editor.foreground": "#d4d4d4",
      "editorLineNumber.foreground": "#54585b",
      "editorLineNumber.activeForeground": "#eda05a",
      "editor.selectionBackground": "#3a3d3f",
      "editor.selectionHighlightBackground": "#2c2f31",
      "editor.lineHighlightBackground": "#202223",
      "editorCursor.foreground": "#eda05a",
      "editorGutter.background": "#1a1b1c",
      "editorIndentGuide.background": "#2c2f31",
      "editorIndentGuide.activeBackground": "#3a3d3f",
      "editorBracketMatch.background": "#3a3d3f",
      "editorBracketMatch.border": "#eda05a",
    },
  });
  themeDefined = true;
}
