// Built-in dark theme, expressed in the v1 theme model (see themes/schema
// for the equivalent JSON shape extension themes use). Registered into the
// theme service at startup like any extension theme.
import { makeBuiltinSpec, type ThemeSpec } from "../themes/themeService";

export const miniCodeDark: ThemeSpec = makeBuiltinSpec({
  id: "mini-code-dark",
  label: "Mini Code Dark",
  base: "vs-dark",
  ui: {
    bg: "#131313",
    panel: "#191a1b",
    border: "#232526",
    text: "#a7acaf",
    textMuted: "#6a7075",
    accent: "#eda05a",
    accentStrong: "#e08a3c",
    error: "#ff5370",
    scrollbar: "#3a3d3f",
    rowHover: "#232526",
    rowActive: "#2c2f31",
  },
  colors: {
    "editor.background": "#1a1b1c",
    "editor.foreground": "#d4d4d4",
    "editorLineNumber.foreground": "#54585b",
    "editorLineNumber.activeForeground": "#eda05a",
    "editor.selectionBackground": "#3a3d3f",
    "editor.selectionHighlightBackground": "#2c2f31",
    "editor.lineHighlightBackground": "#202223",
    "editorCursor.foreground": "#eda05a",
    "editorGutter.background": "#1a1b1c",
    "editorIndentGuide.background": "#2c2f31",
    "editorIndentGuide.activeBackground": "#3a3d3f",
    "editorBracketMatch.background": "#3a3d3f",
    "editorBracketMatch.border": "#eda05a",
    "editorWidget.background": "#1a1b1c",
    "editorWidget.border": "#3a3d3f",
    "editorSuggestWidget.selectedBackground": "#2c2f31",
    "editorHoverWidget.background": "#1a1b1c",
    "editorHoverWidget.border": "#3a3d3f",
    "terminal.background": "#191a1b",
    "terminal.foreground": "#a7acaf",
    "terminalCursor.foreground": "#eda05a",
    "terminal.selectionBackground": "#3a3d3f",
  },
  tokenRules: [
    { token: "comment", foreground: "6a7075", fontStyle: "italic" },
    { token: "comment.java", foreground: "6a7075", fontStyle: "italic" },
    { token: "keyword", foreground: "eda05a", fontStyle: "bold" },
    { token: "keyword.flow", foreground: "eda05a", fontStyle: "bold" },
    { token: "type", foreground: "f4bc86" },
    { token: "type.identifier", foreground: "f4bc86" },
    { token: "type.java", foreground: "f4bc86" },
    { token: "method", foreground: "e5c07b" },
    { token: "method.java", foreground: "e5c07b" },
    { token: "variable", foreground: "9cdcfe" },
    { token: "variable.java", foreground: "9cdcfe" },
    { token: "namespace", foreground: "bb9af7" },
    { token: "namespace.java", foreground: "bb9af7" },
    { token: "identifier", foreground: "d4d4d4" },
    { token: "annotation", foreground: "7dcfff" },
    { token: "delimiter", foreground: "a7acaf" },
    { token: "delimiter.java", foreground: "a7acaf" },
    { token: "number", foreground: "e08a3c" },
    { token: "number.float", foreground: "e08a3c" },
    { token: "number.hex", foreground: "e08a3c" },
    { token: "number.octal", foreground: "e08a3c" },
    { token: "number.binary", foreground: "e08a3c" },
    { token: "number.infinity", foreground: "e08a3c" },
    { token: "number.nan", foreground: "e08a3c" },
    { token: "number.date", foreground: "e08a3c" },
    { token: "string", foreground: "c9d97a" },
    { token: "string.escape", foreground: "e08a3c" },
    { token: "string.invalid", foreground: "ff5370", fontStyle: "underline" },
    { token: "string.java", foreground: "c9d97a" },
    { token: "type.yaml", foreground: "f4bc86" },
    { token: "operators", foreground: "eda05a" },
    { token: "tag", foreground: "7dcfff" },
    { token: "namespace.yaml", foreground: "bb9af7" },
    { token: "meta.directive", foreground: "6a7075", fontStyle: "italic" },
    { token: "metatag", foreground: "eda05a" },
    { token: "attribute.name", foreground: "9cdcfe" },
    { token: "attribute.value", foreground: "c9d97a" },
    { token: "strong", fontStyle: "bold" },
    { token: "emphasis", fontStyle: "italic" },
    { token: "string.link", foreground: "7dcfff", fontStyle: "underline" },
    { token: "string.target", foreground: "a7acaf" },
    { token: "meta.separator", foreground: "6a7075" },
  ],
});
