// Built-in light theme: proves the pipeline handles `base: "vs"` and gives
// users a complete second option without any extension installed.
import { makeBuiltinSpec, type ThemeSpec } from "../themes/themeService";

export const miniCodeLight: ThemeSpec = makeBuiltinSpec({
  id: "mini-code-light",
  label: "Mini Code Light",
  base: "vs",
  ui: {
    bg: "#f2f1ef",
    panel: "#faf9f7",
    border: "#e2ddd5",
    text: "#5b554c",
    textMuted: "#9a938a",
    accent: "#b45f2e",
    accentStrong: "#9c4f24",
    error: "#c93a4b",
    scrollbar: "#cfc8bc",
    rowHover: "#ece7de",
    rowActive: "#e3dccf",
  },
  colors: {
    "editor.background": "#faf9f7",
    "editor.foreground": "#3d3831",
    "editorLineNumber.foreground": "#b3aa9c",
    "editorLineNumber.activeForeground": "#b45f2e",
    "editor.selectionBackground": "#e8dcc8",
    "editor.selectionHighlightBackground": "#f0e8d8",
    "editor.lineHighlightBackground": "#f2ede3",
    "editorCursor.foreground": "#b45f2e",
    "editorGutter.background": "#faf9f7",
    "editorIndentGuide.background": "#e2ddd5",
    "editorIndentGuide.activeBackground": "#cfc8bc",
    "editorBracketMatch.background": "#e8dcc8",
    "editorBracketMatch.border": "#b45f2e",
    "editorWidget.background": "#faf9f7",
    "editorWidget.border": "#e2ddd5",
    "editorSuggestWidget.selectedBackground": "#ece7de",
    "editorHoverWidget.background": "#faf9f7",
    "editorHoverWidget.border": "#e2ddd5",
    "terminal.background": "#faf9f7",
    "terminal.foreground": "#5b554c",
    "terminalCursor.foreground": "#b45f2e",
    "terminal.selectionBackground": "#e8dcc8",
  },
  tokenRules: [
    { token: "comment", foreground: "9a938a", fontStyle: "italic" },
    { token: "keyword", foreground: "b45f2e", fontStyle: "bold" },
    { token: "type", foreground: "8a5a2b" },
    { token: "method", foreground: "6b5ca5" },
    { token: "variable", foreground: "2e6b8a" },
    { token: "namespace", foreground: "7a5fb8" },
    { token: "identifier", foreground: "3d3831" },
    { token: "annotation", foreground: "2e6b8a" },
    { token: "delimiter", foreground: "5b554c" },
    { token: "number", foreground: "9c4f24" },
    { token: "string", foreground: "5a7a2e" },
    { token: "string.escape", foreground: "9c4f24" },
    { token: "string.invalid", foreground: "c93a4b", fontStyle: "underline" },
    { token: "tag", foreground: "2e6b8a" },
    { token: "metatag", foreground: "b45f2e" },
    { token: "strong", fontStyle: "bold" },
    { token: "emphasis", fontStyle: "italic" },
  ],
});
